const GRANT_ERROR_END_TS_LT_NOW = 'GRANT_ERROR_END_TS_LT_NOW';
const GRANT_ERROR_END_TS_GT_SUB_EXP = 'GRANT_ERROR_END_TS_GT_SUB_EXP';
const GRANT_ERROR_RECIPIENT_NOT_FOUND = 'GRANT_ERROR_RECIPIENT_NOT_FOUND';
const GRANT_ERROR_SUB_NOT_FOUND = 'GRANT_ERROR_SUB_NOT_FOUND';
const GRANT_ERROR_SUB_ARCHIVED = 'GRANT_ERROR_SUB_ARCHIVED';
const GRANT_ERROR_SUB_UNPUBLISHED = 'GRANT_ERROR_SUB_UNPUBLISHED';

module.exports = {
    GRANT_ERROR_END_TS_LT_NOW,
    GRANT_ERROR_END_TS_GT_SUB_EXP,
    GRANT_ERROR_RECIPIENT_NOT_FOUND,
    GRANT_ERROR_SUB_NOT_FOUND,
    GRANT_ERROR_SUB_ARCHIVED,
    GRANT_ERROR_SUB_UNPUBLISHED
};
