const KEY_ERROR_KEY_NOT_FOUND = 'KEY_ERROR_KEY_NOT_FOUND';
const KEY_ERROR_USER_NOT_FOUND = 'KEY_ERROR_USER_NOT_FOUND';
const KEY_ERROR_USER_MULTIPLE_KEYS = 'KEY_ERROR_USER_MULTIPLE_KEYS';

module.exports = {
    KEY_ERROR_KEY_NOT_FOUND,
    KEY_ERROR_USER_NOT_FOUND,
    KEY_ERROR_USER_MULTIPLE_KEYS
};
