const SUBS_ERROR_START_TS_LT_NOW = 'SUBS_ERROR_START_TS_LT_NOW';
const SUBS_ERROR_END_TS_LTE_START_TS = 'SUBS_ERROR_END_TS_LTE_START_TS';
const SUBS_ERROR_NAME_ALREADY_EXISTS = 'SUBS_ERROR_NAME_ALREADY_EXISTS';
const SUBS_ERROR_FORBIDDEN_SUB_UNPUBLISHED = 'SUBS_ERROR_FORBIDDEN_SUB_UNPUBLISHED';
const SUBS_ERROR_SUB_NOT_FOUND = 'SUBS_ERROR_SUB_NOT_FOUND';
const SUBS_ERROR_SUB_ALREADY_ARCHIVED = 'SUBS_ERROR_SUB_ALREADY_ARCHIVED';

module.exports = {
    SUBS_ERROR_START_TS_LT_NOW,
    SUBS_ERROR_END_TS_LTE_START_TS,
    SUBS_ERROR_NAME_ALREADY_EXISTS,
    SUBS_ERROR_FORBIDDEN_SUB_UNPUBLISHED,
    SUBS_ERROR_SUB_NOT_FOUND,
    SUBS_ERROR_SUB_ALREADY_ARCHIVED
};
