const ORDER_ERROR_SUB_NOT_FOUND = 'ORDER_ERROR_SUB_NOT_FOUND';
const ORDER_ERROR_SUB_ARCHIVED = 'ORDER_ERROR_SUB_ARCHIVED';
const ORDER_ERROR_SUB_UNPUBLISHED = 'ORDER_ERROR_SUB_UNPUBLISHED';

module.exports = {
    ORDER_ERROR_SUB_NOT_FOUND,
    ORDER_ERROR_SUB_ARCHIVED,
    ORDER_ERROR_SUB_UNPUBLISHED
};
