const AUTH_ERROR_USER_NOT_FOUND = 'AUTH_ERROR_USER_NOT_FOUND';
const AUTH_ERROR_INVALID_PASSWORD = 'AUTH_ERROR_INVALID_PASSWORD';
const AUTH_ERROR_EMAIL_ALREADY_EXISTS = 'AUTH_ERROR_EMAIL_ALREADY_EXISTS';

module.exports = {
    AUTH_ERROR_USER_NOT_FOUND,
    AUTH_ERROR_INVALID_PASSWORD,
    AUTH_ERROR_EMAIL_ALREADY_EXISTS
};
