const AUTH_ERROR_USER_NOT_FOUND = 'AUTH_ERROR_USER_NOT_FOUND';
const AUTH_ERROR_INVALID_PASSWORD = 'AUTH_ERROR_INVALID_PASSWORD';

module.exports = {
    AUTH_ERROR_USER_NOT_FOUND,
    AUTH_ERROR_INVALID_PASSWORD
};
