const USER_ERROR_EMAIL_ALREADY_EXISTS = 'USER_ERROR_EMAIL_ALREADY_EXISTS';
const USER_ERROR_USER_NOT_FOUND = 'USER_ERROR_USER_NOT_FOUND';
const USER_ERROR_SET_ROLE_FORBIDDEN = 'USER_ERROR_SET_ROLE_FORBIDDEN';
const USER_ERROR_SET_IS_ACTIVE_FORBIDDEN = 'USER_ERROR_SET_IS_ACTIVE_FORBIDDEN';

module.exports = {
    USER_ERROR_EMAIL_ALREADY_EXISTS,
    USER_ERROR_USER_NOT_FOUND,
    USER_ERROR_SET_ROLE_FORBIDDEN,
    USER_ERROR_SET_IS_ACTIVE_FORBIDDEN
};
