const USER_ERROR_EMAIL_ALREADY_EXISTS = 'USER_ERROR_EMAIL_ALREADY_EXISTS';
const USER_ERROR_USER_NOT_FOUND = 'USER_ERROR_USER_NOT_FOUND';
const USER_ERROR_FORBIDDEN_SET_ROLE = 'USER_ERROR_FORBIDDEN_SET_ROLE';
const USER_ERROR_FORBIDDEN_SET_IS_ACTIVE = 'USER_ERROR_FORBIDDEN_SET_IS_ACTIVE';

module.exports = {
    USER_ERROR_EMAIL_ALREADY_EXISTS,
    USER_ERROR_USER_NOT_FOUND,
    USER_ERROR_FORBIDDEN_SET_ROLE,
    USER_ERROR_FORBIDDEN_SET_IS_ACTIVE
};
