const REDIS_SESSIONS_NS_PREFIX = 'sess';
const REDIS_SESSIONS_USER_ID_INDEX_NS_PREFIX = 'sess_userid';

const REDIS_SESSIONS_TRACKER_KEY = 'sess_to_be_exp';

module.exports = {
    REDIS_SESSIONS_NS_PREFIX,
    REDIS_SESSIONS_USER_ID_INDEX_NS_PREFIX,
    REDIS_SESSIONS_TRACKER_KEY
};
